config/routes.rb
MusicApp::Application.routes.draw do
  resources :users do
    collection do
      get 'activate'
    end
  end
  resource :session

  resources :bands do
    resources :albums, :only => [:new, :index, :create] do
      resources :tracks, :only => [:new, :index, :create]
    end
  end

  resources :albums, :only => [:show, :edit, :update, :destroy]
  resources :tracks, :only => [:show, :edit, :update, :destroy] do
    resources :notes
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :album_name, :band_id

  belongs_to(
  :band,
  class_name: "Band",
  foreign_key: :band_id,
  primary_key: :id
  )

  has_many(
  :tracks,
  class_name: "Track",
  foreign_key: :album_id,
  primary_key: :id,
  dependent: :destroy
  )

  def self.fetch_by_band_id(band_id)
    Band.find(band_id).albums
  end

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :band_name

  has_many(
  :albums,
  class_name: "Album",
  foreign_key: :band_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many :tracks, :through => :albums, source: :tracks
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :user_id, :track_id, :body

  belongs_to(
  :author,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

  belongs_to(
  :track,
  class_name: "Track",
  foreign_key: :track_id,
  primary_key: :id
  )

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :track_name, :album_id

  belongs_to(
  :album,
  class_name: "Album",
  foreign_key: :album_id,
  primary_key: :id
  )

  has_many(
  :notes,
  class_name: "Note",
  foreign_key: :track_id,
  primary_key: :id,
  dependent: :destroy
  )

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :password_digest, :session_token, :activation_token, :password

  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true

  before_validation :ensure_session_token

  has_many(
  :notes,
  class_name: "Note",
  foreign_key: :user_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many :noted_tracks, :through => :notes, source: :track

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    #may need to set sessions[:session_token] to @session_token
  end

  def password=(secret)
    self.password_digest = BCrypt::Password.create(secret)
  end

  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end

  def self.find_by_credentials(email, secret)
    user = User.find_by_email(email)
    if user.nil?
      flash[:error] ||= []
      flash[:error] << "No user found with this email address"
      return nil
    else
      return user if user.is_password?(secret)
      # flash[:error] ||= []
#       flash[:error] << "Incorrect password for this user!"
      return nil
    end
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      flash[:notice] ||= []
      flash[:notice] << "New Album Created!"
      redirect_to @album
    else
      flash[:notice] ||= []
      flash[:notice] << "Unable to create new album"
      redirect_to new_band_album_url
    end
  end

  def edit
  end

  def update
  end

  def destroy
    album = Album.find(params[:id])
    band = album.band
    Album.destroy(params[:id])
    redirect_to band
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
  end

  def show
    #fail
    @band = Band.find(params[:id])
  end

  def new
  end

  def create
    @band = Band.new(params[:band])
    if @band.save
      flash[:notice] ||= []
      flash[:notice] << "New Band Created!"
      redirect_to @band
    else
      flash[:notice] ||= []
      flash[:notice] << "Unable to create new band"
      redirect_to new_band_url
    end
  end

  def edit
  end

  def update
  end

  def destroy
    Band.destroy(params[:id])
    redirect_to bands_url
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
  end

  def create
    @note = Note.new(params[:note])
    @note.user_id = current_user.id
    if @note.save
      flash[:notice] ||= []
      flash[:notice] << "New Note Created!"
      redirect_to @note.track
    else
      flash[:notice] ||= []
      flash[:notice] << "Unable to create new note"
      redirect_to track_notes_url(params[:track_id])
    end
  end

  def edit
  end

  def update
  end

  def destroy
    note = Note.find(params[:id])
    track = note.track
    Note.destroy(params[:id])
    redirect_to track
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if login_user!(user)
      redirect_to current_user #supposed to go to User#show
    else
      redirect_to new_session_url #go back to sign-in page
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
  end

  def show
    @track = Track.find(params[:id])
  end

  def new
  end

  def create
    @track = Track.new(params[:track])
    if @track.save
      flash[:notice] ||= []
      flash[:notice] << "New Track Created!"
      redirect_to @track
    else
      flash[:notice] ||= []
      flash[:notice] << "Unable to create new track"
      redirect_to new_band_album_track_url
    end
  end

  def edit
  end

  def update
  end

  def destroy
    track = Track.find(params[:id])
    album = track.album
    Track.destroy(params[:id])
    redirect_to album
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
  end

  def create
    @user = User.new(params[:user])
    @user.activated = false
    auth_token = SecureRandom::urlsafe_base64(16)
    @user.activation_token = auth_token
    if @user.save
      #login_user!(@user)
      #
      msg = UserMailer.welcome_email(@user, auth_token)
      msg.deliver!
      redirect_to bands_url
    else
      fail
      flash[:error] ||= []
      flash[:error] << @user.errors.full_messages
      redirect_to new_user_url #need to make sure this is correct
    end
  end

  def show
    redirect_to bands_url
  end

  def activate
    input_token = params[:activation_token]
    @user = User.find_by_activation_token(input_token)
    if @user
      if @user.activated == false
        @user.activated = true
        if @user.save
          login_user!(@user)
          redirect_to bands_url
        else
          flash[:error] ||= []
          flash[:error] << "Can not activate user"
        end
      else
        flash[:notice] ||= []
        flash[:notice] << "User already activated!"
        redirect_to new_session_url
      end
    else
      flash[:error] ||= []
      flash[:error] << "Can not find user!"
      redirect_to new_user_url
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout_user!
    current_user.session_token = nil
    if current_user.save
      session[:session_token] = nil
    else
      flash[:error] ||= []
      flash[:error] << "Can not reset session_token to log in user"
    end
  end

  def login_user!(user)
    user.reset_session_token!
    if user.save && user.activated
      session[:session_token] = user.session_token
      true
    else
      flash[:error] ||= []
      flash[:error] << "User is not activated" if !user.activated
      flash[:error] << "Can not reset session_token to log in user" if !user.save
      false
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<h1> Albums </h1>

  <br>
  List of all albums (or <%= link_to "create new album", new_band_album_url(params[:band_id])%>):
  <br>
  <%Album.all.each do |album|%>
  <%= link_to album.album_name, album %>
  <%end%>

app/views/albums/new.html.erb
<h1>Create a new album!</h1>


<form action="/bands/<%= params[:band_id]%>/albums" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="band_name">Band Name</label>
  <select name="album[band_id]" id="band_id">
  <% Band.all.each do |band| %>
  <option value=<%= band.id %><%"selected" if band.id = params[:band_id]%>><%= band.band_name %></option>
  <%end%>
  <label for="album_name">Album Name</label>
    <input type="text" name="album[album_name]" id="album_name">
  <input type="submit" value="Create Album">
</form>

app/views/albums/show.html.erb
<h1>This is the Album page for <%= @album.album_name %></h1>
<br>
Here is track list (or <%= link_to "create a new track", new_band_album_track_url(@album.band.id, @album.id)%>):
<br>
<%@album.tracks.each do |track|%>
<%= link_to track.track_name, track_url(track.id) %> <%= button_to "Delete Track", track_url(track.id), :method => :delete %>
<% end %>
<br>

app/views/bands/index.html.erb
<h1> Bands </h1>

  <br>
  List of all bands (or <%= link_to "create new band", new_band_url%>):
  <br>
  <% Band.all.each do |band| %>
  <br>
  <%= link_to band.band_name, band %> <%= button_to "Delete Band", band_url(band.id), :method => :delete %>
  <%end%>

app/views/bands/new.html.erb
<h1>Create a new band!</h1>

<form action="/bands" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="band_name">Band Name</label>
    <input type="text" name="band[band_name]" id="band_name">
  <input type="submit" value="Create Band">
</form>

app/views/bands/show.html.erb
<h1>This is the Band page for <%= @band.band_name %></h1>
<br>
Here is an album list (or <%= link_to "create a new album", new_band_album_url(@band.id)%>):
<br><br>
<%@band.albums.each do |album|%>
<%= link_to album.album_name, album_url(album.id) %> <%= button_to "Delete Album", album_url(album.id), :method => :delete %>
<% end %>
<br>

app/views/layouts/_errors.html.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

app/views/layouts/_notices.html.erb
<% if flash[:notice] %>
  <% flash[:notice].each do |notice| %>
    <%= notice %><br>
  <% end %>
<% end %>

app/views/layouts/_sign_in_user.html.erb
<form action="/session" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="user_email">Email</label>
    <input type="text" name="user[email]" id="user_email">
    <br>
  <label for="user_password">Password</label>
    <input type="text" name="user[password]" id="user_password">
    <br>
  <input type="submit" value="Sign in!">
  </form>

app/views/layouts/_sign_up_user.html.erb
<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="user_email">Email</label>
    <input type="text" name="user[email]" id="user_email">
    <br>
  <label for="user_password">Password</label>
    <input type="text" name="user[password]" id="user_password">
    <br>
  <input type="submit" value="Create Account">
  </form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "layouts/errors" %>
<%= render :partial => "layouts/notices" %>
<% if logged_in? %>
<%= "Welcome #{current_user.email}! | "%><%= button_to "sign out", session_url , :method => :delete%>
<% else %>
<%= link_to "Log In", new_session_url %> or <%= link_to "Sign Up", new_user_url %>
<% end %><br>
--------

<%= yield %>

</body>
</html>

app/views/notes/_note.html.erb
<br>
Author: <%= @note.author.email %><br>
Date: <%= @note.created_at %><br>
Note: <%= @note.body %> <br>
<%= button_to "Delete Note", track_note_url(@note.track.id, @note.id), :method => :delete %>

app/views/notes/_note_form.html.erb
<br>
<%if logged_in? %>
  Add Note:
  <form action="/tracks/<%= @track.id %>/notes" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="note[track_id]" value="<%= @track.id %>">
    <label for="comment">Enter Comment</label>
      <textarea name="note[body]" id="comment"></textarea>
    <input type="submit" value="Submit">
  </form>
  <%else%>
  You must <%=link_to "login", new_session_url%> to add notes
  <br>
  <%end%>

app/views/tracks/new.html.erb
<h1>Create a new track!</h1>


<form action="/bands/<%= params[:band_id]%>/albums/<%= params[:album_id]%>/tracks" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="album_name">Album Name</label>
  <select name="track[album_id]" id="album_id">
  <% Album.fetch_by_band_id(params[:band_id]).each do |album| %>
  <option value=<%= album.id %><%"selected" if album.id = params[:album_id]%>><%= album.album_name %></option>
  <%end%>
  <label for="track_name">Track Name</label>
    <input type="text" name="track[track_name]" id="track_name">
  <input type="submit" value="Create Track">
</form>

app/views/tracks/show.html.erb
<h1>This is the Track page for <%= @track.track_name %></h1>
<br>
<%= render 'notes/note_form' %>
<br>

Notes by other users:
<% @track.notes.each do |note|%>
<br>
<%@note = note%>
----
<%= render 'notes/note' %>
<br>
<%end%>

app/views/users/new.html.erb
<h1>Sign Up!</h1>
<br>
Welcome to the Music App!  Fill out the form below to sign up for an account:
<br>
<br>
<%= render 'layouts/sign_up_user' %>